<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

// Autogenerated resources
Route::resource('user', 'UserController');

// Decided to rename the name for the index route to user.list
Route::get('index', 'UserController@index')->name('user.list');

Route::post('user/{user}/upload', 'UserController@upload')->name('user.upload');
